include: package:lint/analysis_options.yaml

linter:
  rules:
    parameter_assignments: true
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: true
    
    # Util classes are awesome!
    avoid_classes_with_only_static_members: true


    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    prefer_double_quotes: false

    # Good packages document everything
    public_member_api_docs: false
    
    # 
    always_specify_types: true
  
    # Back to the 80s
    lines_longer_than_80_chars: true

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error